name: kalabox-ted-testing
#ref: v0.10
#ref: 6aa452131a5ed7c966016b709c66b01cb34b7653
ref: dockerCompose
tags:
  - osx10.11-x64-clean:clean
  - osx10.10-x64-clean:clean
  - ubuntu14.04-x64-clean:clean
#  - osx10.9-x64-clean:clean

#  - ubuntu14.04-x64-clean:clean
#  - win10-x64-clean:bill
files:
  - ./testInstall.js
#  - ./tests.js
